name: eslint

on: [push, pull_request, workflow_dispatch]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - run: yarn check
      - run: yarn lint
