name: eslint

on: [push, pull_request, workflow_dispatch]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Run Svelte Check
        run: bun check
      - name: Run ESLint
        run: bun lint
